#!/bin/bash

set -eu -o pipefail

bold=$(tput bold)
normal=$(tput sgr0)

echo
printf "%sThis will deploy the current code on this machine to the live environment on Firebase%s" "$bold" "$normal"
echo
read -r -p "Continue? [y/N] " -n 1
if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    echo

    # Ensure the app deploy folder exists in the firebase folder
    mkdir -p firebase/dist

    # Clean out an existing build
    rm -rf firebase/dist/app

    # Build the production app and copy the output to the deploy folder
    cd app
    yarn build
    cp -r dist/app/browser/. ../firebase/dist/app

    # Deploy to the live environment
    cd ..
    cd firebase
    yarn deploy:live
fi
